depend on python-packaging
make: Entering directory '/build/python-pygments/src/Pygments-2.10.0/doc'
PYTHONPATH=.. sphinx-build -b html -d _build/doctrees   . _build/html
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==4.3.1', 'console_scripts', 'sphinx-build')())
  File "/usr/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 34, in <module>
    from sphinx.domains import Domain, Index
  File "/usr/lib/python3.10/site-packages/sphinx/domains/__init__.py", line 24, in <module>
    from sphinx.roles import XRefRole
  File "/usr/lib/python3.10/site-packages/sphinx/roles.py", line 20, in <module>
    from sphinx.util.docutils import ReferenceRole, SphinxRole
  File "/usr/lib/python3.10/site-packages/sphinx/util/docutils.py", line 28, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'